globalmessages:
  notAPlayer: "&cErreur, vous n'êtes pas un joueur."
menus:
  enableAffil: # Menu to activate the affiliate system
    title: "    &e&l⚡ &bPLAY.TERRACRAFT.FR &e⚡"
    size: 27
    items:
      1:
        display-name: " "
        lore: ""
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots:
          - 0
          - 1
          - 2
          - 3
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
        event: none
      2:
        display-name: " "
        lore: ""
        material: ORANGE_STAINED_GLASS_PANE
        slots:
          - 4
          - 11
          - 12
          - 14
          - 15
          - 22
        event: none
      3:
        display-name: "&7&l>> &6&lCréer mon adresse"
        lore:
          - " "
          - " "
          - "&7➤ &bInvite le maximum de joueurs à"
          - "&brejoindre le serveur avec ton "
          - "&badresse d'affiliation et obtient"
          - "&bdes récompenses en retour !"
          - ""
          - "&6&k! &r&e20€ À GAGNER CHAQUE MOIS &6&k!"
          - " "
          - " "
          - "&b>> Tu donneras cette adresse"
          - "   &7>> &e%player%.terracraft.fr &7<<"
          - " "
          - " "
          - "    &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
        material: NETHERITE_SCRAP
        slots:
          - 13
        event: create_affiliate_adress