#------------------------------------------------------------
#--------- T E R R A    F F I L L I A T E     CONFIG---------
#------------------------------------------------------------
#         -------------------------------------

# PERMISSIONS :
#               - affiliation.reload --> Reload this configuration file
#               - affiliation.view --> See statistics of a player
#               - affiliation.winner --> Define the winner of the competition
#               - To reset the database, you have to add your minecraft pseudo in operator list bellow
# COMMANDS :
#               - /affiliation --> main command
#               - /affiliation view <player> --> see player stats
#               - /affiliation reload --> reload this configuration
#               - /affiliation reset --> reset database
#               - /affiliation winner <player> --> set the winner
# PLACEHOLDERAPI :
#               - %affiliation_first% --> show the first player of the leaderboard
#               - %affiliation_second% --> show the second player of the leaderboard
#               - %affiliation_third% --> show the third player of the leaderboard
#               - %affiliation_fourth% --> show the fourth player of the leaderboard
#               - YOU CAN GO LIKE THIS UP TO TEN



#-----------                                 ----------------
#------------------------------------------------------------
#--------    DataBase and CloudFlare config     -------------
#------------------!!! NECESSARY !!!-------------------------

# !!!!! CONFIDENTIAL !!!!!
database: # MySQL Database
  host:
  port:
  database:
  user:
  password:
cloudflare: # !!!!! CONFIDENTIAL !!!!!
  #IP Adress to redirect players
  serverIP:
  #Minecraft Server port
  port: #Exemple : 25565
  domain: #Exemple : terracraft.fr
  #CloudFlare API Email (see https://developers.cloudflare.com/api/)
  API_EMAIL:
  #CloudFlare API KEy (see https://developers.cloudflare.com/api/)
  API_KEY:
  #CloudFlare Zone ID (see (see https://developers.cloudflare.com/api/)
  ZONE_ID:
operator: # List of players who are op (to execute /affil reset command to reset database)
  - "YourPseudo"
  - "AnotherPlayer"
  - "ThirdPlayer"

  #--------- T E R R A    F F I L L I A T E     CONFIG---------
  #------------------------------------------------------------





# MENU AND MESSAGES CONFIGURATIONS
globalmessages:
  noPerm: "&cErreur, vous n'avez pas la permission d'effectuer cette commande !"
  notAPlayer: "&cErreur, vous n'êtes pas un joueur."
  unknownCommand: "&cErreur, cette commande n'existe pas !"
  noPlayer: "&cErreur, le joueur ciblé semble être hors ligne !"
  reload: "&f>>> &e&lTerraFfiliate a été mis à jour avec succès !"
competition:
  cashPrize: 40 # Set the cashprize
onJoinWithAffiliateAdress:
  messages:
    connectedSuccessfullyWith:
      - "&7&n                             "
      - " "
      - " "
      - " "
      - "    &e&l⚡ &b&lPLAY.TERRACRAFT.FR &e&l⚡ "
      - " "
      - "&e&l✪ &6&lBienvenue sur TerraCraft ! &e&l✪"
      - " "
      - "&7➤ &bTu es connecté avec l'adresse d'affiliation :"
      - "   &e%affiliateAdress%.terracraft.fr"
      - " "
      - "&7➤ &bTerraCraft te remercie pour ton soutien !"
      - " "
      - "&7➤ &bN'hésite pas à créer ton lien d'affiliation"
      - "   &bet à le partager avec tes amis !"
      - " "
      - "&7&l⚠ &6&lAttention : &7&l⚠"
      - "   &eLes règles du serveur s'appliquent également"
      - "   &eà tes amis parrainés. Assure-toi qu'ils les"
      - "   &eles respectent. Bon jeu !"
      - "     &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
      - " "
      - " "
      - " "
      - "&7&n                             "
affiliateEnabled:
  playSound:
    enable: true
    sound: ENTITY_PLAYER_LEVELUP
  fireworks:
    enable: true
    fireworks:
      type: STAR #STAR/BALL/BALL_LARGE/BRUST/CREEPER
      color-1: Color.BLUE
      color-2: Color.GRAY
      color-3: Color.ORANGE
menu:
  enableAffil: # Menu to activate the affiliate system
    title: "    &e&l⚡ &bPLAY.TERRACRAFT.FR &e⚡ "
    size: 27
    items:
      number: 3
      1:
        display-name: " "
        lore: ""
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots:
          - 0
          - 1
          - 2
          - 3
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
        event: none
      2:
        display-name: " "
        lore: ""
        material: ORANGE_STAINED_GLASS_PANE
        slots:
          - 4
          - 11
          - 12
          - 14
          - 15
          - 22
        event: none
      3:
        display-name: "&7&l>> &6&lCréer mon adresse"
        lore:
          - " "
          - " "
          - "&7➤ &bInvite le maximum de joueurs à"
          - "&brejoindre le serveur avec ton "
          - "&badresse d'affiliation et obtient"
          - "&bdes récompenses en retour !"
          - " "
          - " "
          - "&6&k! &r&e%cashprize%€ À GAGNER CHAQUE MOIS &6&k!"
          - " "
          - " "
          - "&b>> Tu donneras cette adresse"
          - "    &7>> &e%playerip%.terracraft.fr &7<<"
          - " "
          - " "
          - "     &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
        material: BELL
        event: create_affiliate_adress
        slots:
          - 13
  enabledAffil: # Menu who is shown when player already have an affiliate adress
    title: "    &e&l⚡ &bPLAY.TERRACRAFT.FR &e⚡ "
    size: 27
    items:
      number: 2
      1:
        display-name: " "
        lore: ""
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 9
          - 10
          - 11
          - 12
          - 14
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
        event: none
      2:
        display-name: "&7&l &6&lStatistiques"
        lore:
          - "&6&l%player%"
          - " "
          - "&7➤ &bVous avez parrainé &f: &6%affiliateNumber% joueur(s) &b!"
          - "&bVous êtes &e&l%top% e &r&bdans le classement !"
          - "&bContinuez dans cette lancée pour"
          - "&bremporter &e&l%cashprize% euros &r&b!"
          - ""
          - "&7➤ &bVous avez remporté(e)"
          - "&ble concours &e&l%winner% &bfois !"
          - " "
          - "    &6&k! &r&e%cashprize%€ À GAGNER CHAQUE MOIS &6&k!"
          - "       &7>> &e%playerip%.terracraft.fr &7<<"
          - " "
          - " "
          - "         &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
        material: PLAYER_HEAD:%player%
        event: create_affiliate_adress
        slots:
          - 11
      3:
        display-name: "&cDisponible prochaînement"
        lore:
          - ""
          - " "
          - "&7➤ &bNous travaillons chaques jours"
          - "&bpour vous offrir des nouveautés"
          - "&bde façon régulière !"
          - ""
          - "&7➤ &bMerci de jouer sur notre serveur !"
          - " "
          - " &6Psssttt, tu le savais ?"
          - " &7Tout TerraCraft a été construit"
          - " &7par le plus sexy d'entre-nous"
          - " &7SexyVachette !"
          - " "
          - " "
          - "         &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
        material: PUFFERFISH
        event: create_affiliate_adress
        slots:
          - 13
      4:
        display-name: "&cDisponible prochaînement"
        lore:
          - ""
          - " "
          - "&7➤ &bNous travaillons chaques jours"
          - "&bpour vous offrir des nouveautés"
          - "&bde façon régulière !"
          - ""
          - "&7➤ &bMerci de jouer sur notre serveur !"
          - " "
          - " &6Psssttt, tu le savais ?"
          - " &7Ce système d'affiliation a été"
          - " &7développé par l'équipe de dév de"
          - " &7TerraCraft, pour TerraCraft !"
          - " "
          - " "
          - "        &c&l❤ &b&lTERRACRAFT.FR &c&l❤  "
        material: PUFFERFISH
        event: create_affiliate_adress
        slots:
          - 15
      5:
        display-name: " "
        lore:
          - "&7psssttttt... si t'as trouvé cette vitre,"
          -  "&7sache que tu as 5% de réduction sur "
          - "&7la boutique si tu utilises le code"
          - "&7suivant: 'painauchocolat5'"
          - "&7Mais chutttt.. garde le pour toi..."
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots:
          - 8
        event: none