name: TerraFfiliate
version: '${project.version}'
main: fr.manaa.Main
api-version: 1.19
authors: [ Mana ]
softdepend:
  - Bungee-TerraFfiliate
description: Plugin of affiliate system for Minecraft server TerraCraft.fr
commands:
  affiliation:
    aliases:
      - affil
      - aff
      - afl
      - terraffiliation