name: TerraFfiliate
version: '1.0-SNAPSHOT'
main: fr.manaa.Main
api-version: 1.19
authors: [ _Manaa ]
description: Plugin of affiliate system for Minecraft server TerraCraft.fr
commands:
  affil:
  affilreload:
    aliases:
      - affrl